name: jupyter-cadquery
channels:
  - defaults
  - cadquery
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0
  - cadquery=2.1
  - matplotlib=3.3
  - pip:
    #- jupyter-cadquery==2.1.0
    - git+https://github.com/bernhard-42/cadquery-massembly